### ISSUE TITLE
Question about "Failed to get JSON resource"

### ISSUE THREAD

**Issue by jzedu** [rhnvrm/bodhi#1]
Thanks so much for building this!

Right now, I have a problem where I am unable to get the JSON resource when I run this using `hugo server`. In particular I get the following error:

```
Start building sites …
ERROR 2020/11/14 02:48:35 Failed to get JSON resource "https://api.instagram.com/oembed/?url=https://instagram.com/p/BWNjjyYFxVx/&hidecaption=0": Failed to retrieve remote file: Bad Request
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
Built in 287 ms
Error: Error building site: logged 1 error(s)
```
Could you let me know where in your code you are making this request to instagram and how I can remove it? Thank you very much!

**Comment by rhnvrm** [comment]
My preliminary search points to the Instagram shortcut being deprecated, which I have used in the example site. 

https://github.com/gohugoio/hugo/issues/7879

I will remove and push to the repository ASAP.

Thanks for reporting!
